#include <QtTest>
#include <QtEndian>
#include "dvrip.h"
#include <openssl/rsa.h>
#include <openssl/bn.h>
#include <future>
using namespace xm::cloud;
static quint32 u32(const QByteArray &b,int n){return qFromLittleEndian<quint32>(b.constData()+n);}
static quint16 u16(const QByteArray &b,int n){return qFromLittleEndian<quint16>(b.constData()+n);}
static QByteArray slice(quint32 seq,int flags,QByteArray data){QByteArray s(12,0);s.replace(0,4,"XMIP");qToLittleEndian(seq,s.data()+4);s[8]=1;s[9]=char(flags);return s+data;}
class CloudTest:public QObject{
 Q_OBJECT
private slots:
 void parser(){QVERIFY(validSerial("exampleSN12345678"));QVERIFY(!validSerial("a.b.c"));QVERIFY(!validSerial(QString(65,'a')));auto p=packet(1525,32,0x2014);putText(p,4,24,"192.0.2.3");qToLittleEndian<quint16>(8765,p.data()+28);auto e=endpoint(p,4,24,28);QCOMPARE(e.address.toString(),QString("192.0.2.3"));QCOMPARE(e.port,8765);QVERIFY_EXCEPTION_THROWN(endpoint(p.left(29),4,24,28),std::runtime_error);QVERIFY_EXCEPTION_THROWN(putText(p,4,5,"overflow"),std::runtime_error);}
 void crypto(){QByteArray key="0123456789abcdef",json="{\"Ret\":100}";QCOMPARE(aesDecode(aesEncode(json,key),key),json);QVERIFY_EXCEPTION_THROWN(aesDecode("not base64",key),std::runtime_error);QVERIFY_EXCEPTION_THROWN(aesDecode("AAAA",key),std::runtime_error);QByteArray data;for(int i=0;i<200;++i)data+=char(i);auto enc=crypt(data,0xaabbccdd,4);QCOMPARE(crypt(enc,0xaabbccdd,4),data);QCOMPARE(enc.mid(68,12),data.mid(68,12));QVERIFY(enc.mid(64,4)!=data.mid(64,4));QCOMPARE(enc.right(3),data.right(3));
  auto rsa=std::unique_ptr<RSA,decltype(&RSA_free)>(RSA_new(),RSA_free);auto e=std::unique_ptr<BIGNUM,decltype(&BN_free)>(BN_new(),BN_free);BN_set_word(e.get(),65537);QVERIFY(RSA_generate_key_ex(rsa.get(),1024,e.get(),nullptr)==1);const BIGNUM *n,*pub;RSA_get0_key(rsa.get(),&n,&pub,nullptr);char *hex=BN_bn2hex(n);QString publicKey=QString::fromLatin1(hex)+",010001";OPENSSL_free(hex);auto encrypted=QByteArray::fromHex(rsaEncode("example-password-hash",publicKey));QByteArray out(128,0);int count=RSA_private_decrypt(encrypted.size(),reinterpret_cast<const unsigned char*>(encrypted.constData()),reinterpret_cast<unsigned char*>(out.data()),rsa.get(),RSA_PKCS1_PADDING);QCOMPARE(out.left(count),QByteArray("example-password-hash"));QVERIFY_EXCEPTION_THROWN(rsaEncode("x","invalid"),std::runtime_error);
 }
 void ordering(){Receiver r;QVERIFY(r.accept(slice(1,2,"middle")).isEmpty());QVERIFY(r.accept(slice(1,2,"middle")).isEmpty());QVERIFY(r.accept(slice(0,6,"start")).isEmpty());auto done=r.accept(slice(2,10,"end"));QCOMPARE(u32(done,0),14u);QCOMPARE(done.mid(4),QByteArray("startmiddleend"));QVERIFY(r.accept(slice(0,6,"start")).isEmpty());QCOMPARE(quint8(r.ack()[8]),3);QCOMPARE(u32(r.ack(),4),0u);QVERIFY_EXCEPTION_THROWN(r.accept(slice(999,14,"x")),std::runtime_error);Receiver broken;QVERIFY_EXCEPTION_THROWN(broken.accept(slice(0,10,"end")),std::runtime_error);Receiver conflict;conflict.accept(slice(1,10,"a"));QVERIFY_EXCEPTION_THROWN(conflict.accept(slice(1,10,"b")),std::runtime_error);}
 void cancellation(){std::atomic_bool stop{true};Transport t(stop);QElapsedTimer clock;clock.start();QVERIFY_EXCEPTION_THROWN(t.open("exampleSN12345678","127.0.0.1"),std::runtime_error);QVERIFY(clock.elapsed()<300);}
 void mockRelay_data(){QTest::addColumn<int>("mode");QTest::newRow("loss and reordering")<<0;QTest::newRow("encrypted login and control")<<1;QTest::newRow("authentication rejection")<<2;QTest::newRow("cloud playback")<<3;}
 void mockRelay(){QFETCH(int,mode);
  auto rsa=std::unique_ptr<RSA,decltype(&RSA_free)>(RSA_new(),RSA_free);auto exponent=std::unique_ptr<BIGNUM,decltype(&BN_free)>(BN_new(),BN_free);BN_set_word(exponent.get(),65537);QVERIFY(RSA_generate_key_ex(rsa.get(),1024,exponent.get(),nullptr)==1);const BIGNUM *modulus;RSA_get0_key(rsa.get(),&modulus,nullptr,nullptr);char *hex=BN_bn2hex(modulus);QString publicKey=QString::fromLatin1(hex)+",010001";OPENSSL_free(hex);QByteArray sessionKey;int loginRequests=0,stopRequests=0;QMap<quint16,quint32> responseSequences;quint16 mediaPort=0;
  auto decryptCredential=[&](QString value){auto data=QByteArray::fromHex(value.toLatin1());QByteArray out(128,0);int n=RSA_private_decrypt(data.size(),reinterpret_cast<const unsigned char*>(data.constData()),reinterpret_cast<unsigned char*>(out.data()),rsa.get(),RSA_PKCS1_PADDING);if(n<0)throw std::runtime_error("Invalid test RSA credential");return out.left(n);};
  QUdpSocket bootstrap,directory,rendezvous,relay;
  QVERIFY(bootstrap.bind(QHostAddress::LocalHost,7999));QVERIFY(directory.bind(QHostAddress::LocalHost,8777));QVERIFY(rendezvous.bind(QHostAddress::LocalHost,8765));QVERIFY(relay.bind(QHostAddress::LocalHost,4999));
  QByteArray uuid;quint32 id=0;constexpr quint32 peer=1024,key=0x12345678;int sends=0,pings=0;QString error;QMap<quint16,Receiver> receivers;
  auto bind=[&](QUdpSocket &socket,auto fn){connect(&socket,&QUdpSocket::readyRead,this,[&,fn,ptr=&socket]{while(ptr->hasPendingDatagrams()){auto d=ptr->receiveDatagram();try{fn(d);}catch(const std::exception &e){error=QString::fromUtf8(e.what());}}});};
  bind(bootstrap,[&](QNetworkDatagram d){QCOMPARE(u16(d.data(),2),1524);auto p=packet(1525,32,0x2014);putText(p,4,24,"127.0.0.1");qToLittleEndian<quint16>(8765,p.data()+28);bootstrap.writeDatagram(p,d.senderAddress(),d.senderPort());});
  bind(directory,[&](QNetworkDatagram d){QCOMPARE(d.data().mid(4),QByteArray("exampleSN12345678\0",18));auto p=packet(0xb001,140,0x2015);qToLittleEndian<quint32>(1,p.data()+4);putText(p,8,100,"exampleSN12345678");putText(p,108,20,"127.0.0.1");qToLittleEndian<quint16>(8765,p.data()+128);directory.writeDatagram(p,d.senderAddress(),d.senderPort());});
  bind(rendezvous,[&](QNetworkDatagram d){auto data=d.data();if(u16(data,2)==1000){auto p=packet(1001,24);putText(p,4,16,"127.0.0.1");qToLittleEndian(d.senderPort(),p.data()+20);rendezvous.writeDatagram(p,d.senderAddress(),d.senderPort());return;}
   QCOMPARE(u16(data,2),1004);id=u32(data,4);uuid=data.mid(8,100).split('\0')[0];auto p=packet(1005,24);qToLittleEndian(id,p.data()+4);qToLittleEndian<quint32>(1,p.data()+8);qToLittleEndian(key,p.data()+20);rendezvous.writeDatagram(p,d.senderAddress(),d.senderPort());p=packet(1004,360);qToLittleEndian(peer,p.data()+4);putText(p,8,100,"exampleSN12345678");putText(p,108,100,uuid);qToLittleEndian(id,p.data()+328);putText(p,332,16,"127.0.0.1");qToLittleEndian<quint16>(4999,p.data()+348);rendezvous.writeDatagram(p,d.senderAddress(),d.senderPort());});
  auto wrap=[](QByteArray s){auto p=packet(2003,12+s.size());qToLittleEndian<quint16>(s.size(),p.data()+6);p.replace(12,s.size(),s);return p;};
  bind(relay,[&](QNetworkDatagram d){auto data=d.data();auto cmd=u16(data,2);if(cmd==2002){++pings;QCOMPARE(data.size(),8);QCOMPARE(u16(data,6),0);return;}if(cmd==3001){relay.writeDatagram(packet(3002,8),d.senderAddress(),d.senderPort());return;}if(cmd==2000){for(auto reply:{2000,2001}){auto p=packet(reply,112);qToLittleEndian(peer,p.data()+4);putText(p,8,100,"exampleSN12345678");qToLittleEndian<quint32>(0x20001,p.data()+108);relay.writeDatagram(p,d.senderAddress(),d.senderPort());}return;}if(cmd!=2003||quint8(data[21])&1)return;
   ++sends; // Lose the first packet to require a retransmission.
   if(sends==1)return;
   auto &incoming=receivers[d.senderPort()];auto &responseSequence=responseSequences[d.senderPort()];auto decodedSlice=data.mid(12);decodedSlice.replace(12,decodedSlice.size()-12,crypt(decodedSlice.mid(12),key,4));auto message=incoming.accept(decodedSlice);relay.writeDatagram(wrap(incoming.ack()),d.senderAddress(),d.senderPort());if(message.isEmpty())return;
   auto plain=message.mid(4);
   if(mode){QVERIFY(plain.size()>=20);auto command=u16(plain,14);auto body=plain.mid(20);while(body.endsWith('\0')||body.endsWith('\n'))body.chop(1);quint16 replyId=0;quint32 sid=42;QByteArray response;
    if(command==1413){replyId=1414;sid=1099999;QJsonObject cap{{"Ret",100},{"Bits",1024},{"EncryptAlgo","RSA_V1.5"},{"PublicKey",publicKey},{"LoginEncryptionType",QJsonObject{{"RSA",true}}},{"DataEncryptionType",QJsonObject{{"AES",true}}},{"NotEncryptMsgID",QJsonArray{1000,1001,1412,1413,1414,1422,1424,1425}}};response=aesEncode(QJsonDocument(cap).toJson(QJsonDocument::Compact),wrapperKey())+QByteArray(1,0);}
    else if(command==1000){++loginRequests;QCOMPARE(quint8(plain[12]),99);auto creds=QJsonDocument::fromJson(aesDecode(body,wrapperKey())).object();QCOMPARE(decryptCredential(creds["UserName"].toString()),QByteArray("test-user"));QCOMPARE(decryptCredential(creds["PassWord"].toString()),xm::digest("test-password").toLatin1());sessionKey=decryptCredential(creds["CommunicateKey"].toString());QCOMPARE(sessionKey.size(),16);replyId=1001;response=QJsonDocument(QJsonObject{{"Ret",mode==2?101:100},{"ChannelNum",4},{"DataUseAES",false}}).toJson(QJsonDocument::Compact)+QByteArray(1,0);}
    else if(command==1020){QCOMPARE(QJsonDocument::fromJson(aesDecode(body,sessionKey)).object()["Name"].toString(),QString("SystemInfo"));replyId=1021;response=aesEncode(QJsonDocument(QJsonObject{{"Ret",100},{"SystemInfo",QJsonObject{{"VideoInChannel",4}}}}).toJson(QJsonDocument::Compact),sessionKey)+QByteArray(1,0);}
    else if(command==1424){QCOMPARE(u32(plain,4),42u);auto claim=QJsonDocument::fromJson(body).object()["OPPlayBack"].toObject();QCOMPARE(claim["Action"].toString(),QString("Claim"));auto parameter=claim["Parameter"].toObject();QCOMPARE(parameter["PlayMode"].toString(),QString("ByTime"));QCOMPARE(parameter["FileName"].toString(),QString("01_2026-09-11 12:00:00"));QVERIFY(!parameter.contains("Channel"));mediaPort=d.senderPort();replyId=1425;response="{\"Ret\":100}";}
    else if(command==1420){QCOMPARE(qFromLittleEndian<quint16>(plain.constData()+12),quint16(1));auto claim=QJsonDocument::fromJson(aesDecode(body,sessionKey)).object()["OPPlayBack"].toObject();if(claim["Action"]=="Stop"){++stopRequests;return;}QCOMPARE(claim["Action"].toString(),QString("Start"));QVERIFY(mediaPort!=0);QVERIFY(mediaPort!=d.senderPort());replyId=1421;response=aesEncode("{\"Ret\":100}",sessionKey)+QByteArray(1,0);
     auto nal=QByteArray::fromHex("00000001658884");auto frame=QByteArray::fromHex("000001fc021900000000000000000000");qToLittleEndian<quint32>(nal.size(),frame.data()+12);frame+=nal;auto bytes=xm::header(42,0,1422,frame.size())+frame;relay.writeDatagram(wrap(slice(responseSequences[mediaPort]++,14,crypt(bytes,key,4))),d.senderAddress(),mediaPort);
    }
    else {QFAIL("Unexpected command");}
    auto encoded=xm::header(sid,0,replyId,response.size())+response;for(int offset=0;offset<encoded.size();offset+=1268){auto part=encoded.mid(offset,1268);int flags=2|(offset==0?4:0)|(offset+part.size()==encoded.size()?8:0);relay.writeDatagram(wrap(slice(responseSequence++,flags,crypt(part,key,4))),d.senderAddress(),d.senderPort());}return;
   }
   QCOMPARE(plain,QByteArray(3001,'q'));QByteArray body(3000,'v');auto enc=body;
   // Duplicate and reorder middle slices; receiver must still return one message.
   for(int seq:{1,1,0,2}){int offset=seq*1268;auto part=enc.mid(offset,1268);auto p=wrap(slice(seq,2|(seq==0?4:0)|(seq==2?8:0),crypt(part,key,4)));relay.writeDatagram(p,d.senderAddress(),d.senderPort());}
  });
  std::atomic_bool stop{false};auto future=std::async(std::launch::async,[&]{if(mode){xm::Client client(stop);QUrl url("dvrip://test-user:test-password@xmeye-cloud?cloudId=exampleSN12345678&bootstrap=127.0.0.1");if(mode==3){QUrlQuery query(url);query.addQueryItem("archiveFile","time");query.addQueryItem("playMode","ByTime");query.addQueryItem("channel","1");query.addQueryItem("begin","2026-09-11 12:00:00");query.addQueryItem("end","2026-09-11 12:05:00");url.setQuery(query);client.open(url);if(client.readVideo()!=QByteArray::fromHex("00000001658884"))throw std::runtime_error("Playback bytes differ");return QByteArray("4");}int n=client.scanChannels(url);auto info=client.control(1020,"SystemInfo");if(info["SystemInfo"].toObject()["VideoInChannel"].toInt()!=4)throw std::runtime_error("Invalid test control response");return QByteArray::number(n);}Transport t(stop);t.open("exampleSN12345678","127.0.0.1");t.write(QByteArray(3001,'q'));QByteArray received;for(int i=0;i<30;++i){received+=t.read(100);QThread::msleep(80);}for(int i=0;i<25;++i){t.service();QThread::msleep(100);}return received;});QElapsedTimer clock;clock.start();while(future.wait_for(std::chrono::milliseconds(0))!=std::future_status::ready&&clock.elapsed()<15000)QTest::qWait(10);stop=true;QVERIFY(future.wait_for(std::chrono::seconds(1))==std::future_status::ready);try{auto result=future.get();QVERIFY(mode!=2);QCOMPARE(result,mode?QByteArray("4"):QByteArray(3000,'v'));}catch(const std::exception &e){if(mode!=2)QFAIL(e.what());QVERIFY(QString::fromUtf8(e.what()).contains("code 101"));}if(mode==3)QTRY_COMPARE_WITH_TIMEOUT(stopRequests,1,1000);if(mode)QCOMPARE(loginRequests,1);QVERIFY(error.isEmpty());QVERIFY(sends>=2);if(!mode)QVERIFY(pings>=2);
 }
};
QTEST_GUILESS_MAIN(CloudTest)
#include "cloud_test.moc"
