#!/usr/bin/env bash
# Generated by OpenAI Codex for OpenWatch. Native Linux / MSYS2 UCRT64 builds.
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
build_dir=''
jobs=2
run_tests=OFF
package=''
usage() {
  cat <<'HELP'
Usage: bash scripts/build.sh [--build-dir PATH] [--jobs N] [--test] [--package TGZ|DEB]
Build a native Release executable on Linux or Windows (MSYS2 UCRT64).
  --build-dir PATH   Build directory (default: <source>/build/linux or windows)
  --jobs N           Parallel compiler jobs (default: 2)
  --test             Build and run tests, then an offscreen startup check
  --package TGZ|DEB  Linux system-dependency package; not a bundled AppImage
  --help            Show this help
Dependencies must already be installed; see README.md. No sudo/install is run.
Windows output needs UCRT64 runtime DLLs; run it inside the UCRT64 shell.
This script is not a cross-compiler or a Windows portable-package assembler.
HELP
}
fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
while (($#)); do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --build-dir|--jobs|--package)
      (($#>=2)) || fail "Missing value for $1"
      case "$1" in
        --build-dir) build_dir=$2 ;;
        --jobs) jobs=$2 ;;
        --package) package=$2 ;;
      esac
      shift 2 ;;
    --test) run_tests=ON; shift ;;
    *) fail "Unknown option: $1 (use --help)" ;;
  esac
done
[[ "$jobs" =~ ^[1-9][0-9]*$ ]] || fail '--jobs must be a positive integer'
[[ -z "$package" || "$package" == TGZ || "$package" == DEB ]] || fail 'Package must be TGZ or DEB'
case "$(uname -s)" in
  Linux*) platform=linux; executable=openwatch; generator=() ;;
  MINGW*|MSYS*|UCRT*)
    [[ ${MSYSTEM:-} == UCRT64 ]] || fail 'Open the MSYS2 UCRT64 terminal, not MSYS, MINGW64, Git Bash or WSL.'
    [[ -z "$package" ]] || fail '--package is for Linux; see Windows deployment notes in README.md'
    platform=windows; executable=openwatch.exe; generator=(-G Ninja)
    for tool in cmake gcc pkg-config; do
      path=$(command -v "$tool") || fail "Missing $tool; install the UCRT64 dependencies"
      [[ "$path" == /ucrt64/bin/* ]] || fail "$tool must come from /ucrt64/bin (found $path)"
    done
    ;;
  *) fail 'Supported hosts: Linux and Windows with MSYS2 UCRT64' ;;
esac
for tool in cmake pkg-config; do command -v "$tool" >/dev/null || fail "Missing $tool; see README dependencies"; done
pkg-config --exists libavformat libavcodec libavutil libswscale libswresample sdl2 openssl || fail 'Missing FFmpeg, SDL2 or OpenSSL development packages'
if [[ "$run_tests" == ON && "$platform" == linux ]]; then
  for tool in python3 ffmpeg ffprobe; do command -v "$tool" >/dev/null || fail "Tests require $tool"; done
  encoders=$(ffmpeg -hide_banner -encoders 2>/dev/null)
  [[ "$encoders" == *libx264* && "$encoders" == *libx265* ]] || fail 'Integration tests require FFmpeg libx264 and libx265 encoders'
fi
if [[ -z "$build_dir" ]]; then build_dir="$root/build/$platform"; fi
mkdir -p -- "$build_dir"
build_dir=$(cd -- "$build_dir" && pwd)
[[ "$build_dir" != "$root" ]] || fail 'Choose a separate build directory, not the source root'
printf 'Building OpenWatch for %s in %s\n' "$platform" "$build_dir"
cmake -S "$root" -B "$build_dir" "${generator[@]}" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING="$run_tests"
cmake --build "$build_dir" --parallel "$jobs"
if [[ "$run_tests" == ON ]]; then
  if [[ "$platform" == windows ]]; then
    # Python/network media fixtures are verified on Linux, not Windows.
    ctest --test-dir "$build_dir" --output-on-failure -R '^(protocol|recorder_scan|navigation|discovery_onvif|device_management|zoom_recording|controls_vault|archive_timeline)$'
  else
    ctest --test-dir "$build_dir" --output-on-failure
  fi
  QT_QPA_PLATFORM=offscreen "$build_dir/$executable" --smoke-test
fi
if [[ -n "$package" ]]; then
  (cd -- "$build_dir" && cpack -G "$package" -B "$build_dir/packages")
fi
printf '\nExecutable: %s/%s\n' "$build_dir" "$executable"
printf 'Run it directly; no package installation is required.\n'
