#include "archivedialog.h"
ArchiveDialog::ArchiveDialog(QUrl initial,QWidget *parent):QDialog(parent){
 setWindowTitle("NVR playback");resize(1180,760);auto *root=new QVBoxLayout(this);
 auto *heading=new QHBoxLayout;auto *title=new QLabel("NVR playback");title->setStyleSheet("font-size:22px;font-weight:600");heading->addWidget(title);heading->addStretch();auto *settings=new QPushButton("Connection settings");heading->addWidget(settings);root->addLayout(heading);
 connection=new QWidget;auto *form=new QHBoxLayout(connection);host=new QLineEdit(initial.host());host->setPlaceholderText("Recorder IP");port=new QSpinBox;port->setRange(1,65535);port->setValue(initial.port(34567));user=new QLineEdit(initial.userName().isEmpty()?"admin":initial.userName());password=new QLineEdit(initial.password());password->setEchoMode(QLineEdit::Password);for(auto pair:QList<QPair<QString,QWidget*>>{{"IP",host},{"Port",port},{"User",user},{"Password",password}}){form->addWidget(new QLabel(pair.first));form->addWidget(pair.second);}root->addWidget(connection);connection->setVisible(initial.host().isEmpty());connect(settings,&QPushButton::clicked,this,[this]{connection->setVisible(!connection->isVisible());});
 auto *body=new QHBoxLayout;root->addLayout(body,1);auto *side=new QVBoxLayout;body->addLayout(side);calendar=new QCalendarWidget;calendar->setGridVisible(false);QTextCharFormat header;header.setBackground(QColor("#1c2b3d"));header.setForeground(QColor("#b5c9da"));calendar->setHeaderTextFormat(header);calendar->setVerticalHeaderFormat(QCalendarWidget::NoVerticalHeader);calendar->setMaximumWidth(300);side->addWidget(calendar);side->addWidget(new QLabel("Channels · up to 4, separated by commas"));channelText=new QLineEdit(QString::number(QUrlQuery(initial).queryItemValue("channel").toInt()+1));channelText->setObjectName("archiveChannels");side->addWidget(channelText);search=new QPushButton("Load day");side->addWidget(search);status=new QLabel("Choose channels and a date, then load the day.");status->setWordWrap(true);status->setTextFormat(Qt::PlainText);status->setMaximumWidth(300);side->addWidget(status);side->addStretch();auto *help=new QLabel("Drag timeline to seek\n← / →  10 seconds\nShift + ← / →  1 minute\nSpace  pause / resume\nDouble-click camera  focus / grid\n\nRecorder's local time · Video only\nStream timestamps · Speed depends on delivery.");help->setWordWrap(true);side->addWidget(help);
 auto *right=new QVBoxLayout;body->addLayout(right,1);auto *viewbar=new QHBoxLayout;viewbar->addWidget(new QLabel("VIEW"));layoutMode=new QComboBox;layoutMode->addItems({"All selected cameras","Single camera"});viewbar->addWidget(layoutMode);viewbar->addStretch();clockLabel=new QLabel("00:00:00");clockLabel->setStyleSheet("font-size:20px;color:#ffd27c");viewbar->addWidget(clockLabel);right->addLayout(viewbar);grid=new QGridLayout;right->addLayout(grid,1);
 for(int i=0;i<4;++i){auto &v=views[i];v.panel=new QWidget;auto *box=new QVBoxLayout(v.panel);box->setContentsMargins(2,2,2,2);v.picture=new QLabel("No recordings loaded");v.picture->setAlignment(Qt::AlignCenter);v.picture->setMinimumSize(100,80);v.picture->setSizePolicy(QSizePolicy::Ignored,QSizePolicy::Ignored);v.picture->setStyleSheet("background:#080e15;border:1px solid #304454");v.picture->setFocusPolicy(Qt::StrongFocus);v.picture->installEventFilter(this);v.label=new QLabel;v.label->setTextFormat(Qt::PlainText);box->addWidget(v.picture,1);box->addWidget(v.label);}
 timeline=new archive::Timeline;right->addWidget(timeline);timeline->scrub=[this](int n,bool commit){dragging=!commit;showTime(n);if(commit)seek(n);};
 auto *transport=new QHBoxLayout;right->addLayout(transport);auto *back=new QPushButton("−10s");toggle=new QPushButton("Play");auto *forward=new QPushButton("+10s");time=new QTimeEdit(QTime(0,0));time->setDisplayFormat("HH:mm:ss");auto *go=new QPushButton("Go");auto *zoom=new QComboBox;zoom->addItems({"24 hours","6 hours","1 hour","15 minutes"});speed=new QComboBox;speed->addItems({"0.25×","0.5×","1×","2×","4×","8×"});speed->setCurrentIndex(2);speed->setToolTip("Playback speed · faster rates depend on recorder delivery and bandwidth");connect(speed,&QComboBox::currentIndexChanged,this,[this]{if(playing)seek(cursor);});for(auto *w:QList<QWidget*>{back,toggle,forward,time,go,zoom,speed})transport->addWidget(w);
 seekTimer=new QTimer(this);seekTimer->setSingleShot(true);seekTimer->setInterval(180);connect(seekTimer,&QTimer::timeout,this,[this]{seek(cursor);});connect(back,&QPushButton::clicked,this,[this]{step(-10);});connect(forward,&QPushButton::clicked,this,[this]{step(10);});connect(go,&QPushButton::clicked,this,[this]{seek(QTime(0,0).secsTo(time->time()));});connect(zoom,&QComboBox::currentIndexChanged,this,[this](int n){timeline->zoom(QList<int>{86400,21600,3600,900}[n]);});connect(toggle,&QPushButton::clicked,this,[this]{if(playing)stop();else seek(cursor);});connect(layoutMode,&QComboBox::currentIndexChanged,this,[this]{arrange();});connect(search,&QPushButton::clicked,this,[this]{if(worker&&worker->isRunning()){cancelled=true;search->setEnabled(false);status->setText("Cancelling search…");}else searchDay();});
 connect(calendar,&QCalendarWidget::selectionChanged,this,[this]{if(!clips.isEmpty()&&(!worker||!worker->isRunning()))searchDay();});
 auto shortcut=[&](QKeySequence key,std::function<void()> action){auto *s=new QShortcut(key,this);s->setContext(Qt::WidgetWithChildrenShortcut);connect(s,&QShortcut::activated,this,action);connect(qApp,&QApplication::focusChanged,s,[this,s](QWidget*,QWidget *w){s->setEnabled(!qobject_cast<QLineEdit*>(w)&&!qobject_cast<QAbstractSpinBox*>(w)&&!qobject_cast<QComboBox*>(w)&&!(w&&calendar->isAncestorOf(w)));});};shortcut(Qt::Key_Left,[this]{step(-10);});shortcut(Qt::Key_Right,[this]{step(10);});shortcut(QKeySequence(Qt::SHIFT|Qt::Key_Left),[this]{step(-60);});shortcut(QKeySequence(Qt::SHIFT|Qt::Key_Right),[this]{step(60);});shortcut(Qt::Key_Space,[this]{toggle->click();});
 auto *timer=new QTimer(this);connect(timer,&QTimer::timeout,this,&ArchiveDialog::refresh);timer->start(80);arrange();
}
ArchiveDialog::~ArchiveDialog(){cancelled=true;if(worker){worker->wait();delete worker;}stop();}
void ArchiveDialog::reject(){cancelled=true;stop();QDialog::reject();}
void ArchiveDialog::stop(){playing=false;seekTimer->stop();for(auto &v:views)v.video.requestStop();toggle->setText("Play");}
void ArchiveDialog::arrange(){for(auto &v:views){grid->removeWidget(v.panel);v.panel->hide();}int count=qMax(1,int(selectedChannels.size()));for(int i=0;i<count;++i){if(layoutMode->currentIndex()==1&&i!=focused)continue;grid->addWidget(views[i].panel,layoutMode->currentIndex()==1?0:i/2,layoutMode->currentIndex()==1?0:i%2);views[i].panel->show();}}
bool ArchiveDialog::eventFilter(QObject *o,QEvent *e){for(int i=0;i<4;++i)if(o==views[i].picture){if(e->type()==QEvent::MouseButtonPress){focused=i;views[i].picture->setFocus();}if(e->type()==QEvent::MouseButtonDblClick){focused=i;layoutMode->setCurrentIndex(1-layoutMode->currentIndex());return true;}}return QDialog::eventFilter(o,e);}
void ArchiveDialog::showTime(int n){clockLabel->setText(QTime(0,0).addSecs(n).toString("HH:mm:ss"));if(!time->hasFocus())time->setTime(QTime(0,0).addSecs(n));}
void ArchiveDialog::step(int n){cursor=qBound(0,cursor+n,86399);timeline->setPosition(cursor);showTime(cursor);seekTimer->start();}
void ArchiveDialog::openView(int i,int second){auto &v=views[i];v.clip=archive::at(clips,selectedChannels[i],second);v.video.requestStop();v.picture->setText(v.clip<0?"No recording at this time":"Opening recording…");if(v.clip<0)return;auto c=clips[v.clip];v.start=second;QUrl url=source;QUrlQuery q;q.addQueryItem("speed",QString::number(QList<double>{.25,.5,1,2,4,8}[speed->currentIndex()]));q.addQueryItem("channel",QString::number(c.channel));q.addQueryItem("archiveFile",c.name);auto stamp=[this](int s){return day.toString("yyyy-MM-dd")+" "+QTime(0,0).addSecs(qMin(s,86399)).toString("HH:mm:ss");};q.addQueryItem("begin",stamp(second));q.addQueryItem("end",stamp(c.end));url.setQuery(q);v.video.start(url);}
void ArchiveDialog::seek(int second){if(clips.isEmpty())return;stop();cursor=qBound(0,second,86399);for(auto &v:views)v.video.requestStop();for(int i=0;i<selectedChannels.size();++i)openView(i,cursor);playing=true;toggle->setText("Pause");gapStart=cursor;gapClock.restart();timeline->setPosition(cursor);showTime(cursor);}
void ArchiveDialog::refresh(){
 int lead=-1,priority=-1;bool unknownTime=false;bool active=false;QVector<int> completed;
 for(int i=0;i<selectedChannels.size();++i){auto &v=views[i];auto shown=v.video.archiveFrame();
  if(v.clip>=0&&!shown.first.isNull())v.picture->setPixmap(QPixmap::fromImage(shown.first).scaled(v.picture->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));
  QString state=v.clip<0?"No footage":v.video.status();
  if(v.clip>=0&&!shown.first.isNull()){
   if(shown.second>=0){auto dt=QDateTime::fromMSecsSinceEpoch(shown.second,Qt::UTC);state+=" · "+dt.toString("HH:mm:ss");int rank=v.video.status()=="Playback complete"?0:(i==focused?2:1);if(dt.date()==day&&rank>priority){lead=QTime(0,0).secsTo(dt.time());priority=rank;}}
   else {state+=" · Recording timestamp unavailable";unknownTime=true;}
  }
  v.label->setText(QString("CH %1 · %2").arg(selectedChannels[i]+1).arg(state));
  if(v.clip>=0){if(v.video.status()=="Playback complete")completed.append(i);else if(v.video.status().startsWith("Playback")||v.video.status().startsWith("Connecting"))active=true;}
 }
 if(!playing||dragging||seekTimer->isActive())return;
 if(lead>=0){cursor=lead;timeline->setPosition(cursor);showTime(cursor);}else if(unknownTime)clockLabel->setText("--:--:--");
 // File end metadata selects the next file, never the displayed time.
 for(int i:completed){int finish=clips[views[i].clip].end;int next=-1;for(int j=0;j<clips.size();++j)if(clips[j].channel==selectedChannels[i]&&clips[j].begin>=finish){next=j;break;}
  if(next>=0){openView(i,clips[next].begin);active=true;}
 }
 for(int i=0;i<selectedChannels.size();++i)if(views[i].clip<0&&archive::at(clips,selectedChannels[i],cursor)>=0){openView(i,cursor);active=true;}
 if(!active)stop();
}
void ArchiveDialog::searchDay(){auto selected=archive::channels(channelText->text());if(selected.isEmpty()){status->setText("Enter 1–4 channel numbers, for example 1,2,3,4.");return;}if(host->text().trimmed().isEmpty()){connection->show();status->setText("Enter the recorder IP and login details.");return;}stop();for(auto &v:views){v.video.requestStop();v.clip=-1;v.picture->setText("Loading day…");}if(worker){worker->wait();delete worker;worker=nullptr;}source=QUrl();source.setScheme("dvrip");source.setHost(host->text().trimmed());source.setPort(port->value());source.setUserName(user->text());source.setPassword(password->text());day=calendar->selectedDate();selectedChannels=selected;focused=0;clips.clear();result.clear();error.clear();timeline->clips.clear();timeline->channels=selected;timeline->update();arrange();cancelled=false;search->setText("Cancel search");calendar->setEnabled(false);channelText->setEnabled(false);connection->setEnabled(false);status->setText("Loading recording coverage… Empty day searches retry hourly windows; Cancel stops the search.");
 worker=QThread::create([this]{for(int ch:selectedChannels){QString begin=day.toString("yyyy-MM-dd")+" 00:00:00",end=day.toString("yyyy-MM-dd")+" 23:59:59";QSet<QString> seen;try{for(int page=0;page<128&&!cancelled;++page){xm::Client client(cancelled);auto rows=client.recordings(source,ch,begin,end);if(page==0&&rows.isEmpty())error+=QString("CH %1: no matches after standard, compatible and hourly searches. ").arg(ch+1);QString latest=begin;for(auto value:rows){auto o=value.toObject();QString name=o["FileName"].toString(),b=o["BeginTime"].toString(),e=o["EndTime"].toString();auto bt=QDateTime::fromString(b,"yyyy-MM-dd HH:mm:ss"),et=QDateTime::fromString(e,"yyyy-MM-dd HH:mm:ss");if(name.isEmpty()||!bt.isValid()||!et.isValid()||b>=e)continue;latest=qMax(latest,b);if(seen.contains(name))continue;seen.insert(name);int from=bt.date()<day?0:QTime(0,0).secsTo(bt.time()),to=et.date()>day?86400:QTime(0,0).secsTo(et.time());result.append({ch,from,to,name});}if(rows.size()<64)break;if(latest<=begin||page==127){error+=QString("CH %1: coverage may be incomplete. ").arg(ch+1);break;}begin=latest;}}catch(const std::exception &e){error+=QString("CH %1: %2 ").arg(ch+1).arg(e.what());}if(cancelled)break;}});
 connect(worker,&QThread::finished,this,[this]{worker->wait();calendar->setEnabled(true);channelText->setEnabled(true);connection->setEnabled(true);search->setEnabled(true);search->setText("Load day");clips=result;if(clips.isEmpty()&&error.isEmpty()&&!cancelled)error="No matches from either recording search format. If XMEye shows footage for the same channel/date, recorder-specific search compatibility still needs investigation.";std::sort(clips.begin(),clips.end(),[](auto a,auto b){return a.begin<b.begin;});timeline->clips=clips;timeline->update();status->setText(QString("%1 · %2 recordings%3\n%4").arg(day.toString("ddd, MMM d")).arg(clips.size()).arg(cancelled?" · search cancelled":"").arg(error));for(auto &v:views)v.picture->setText("Select a time on the timeline");if(!clips.isEmpty()){cursor=clips.first().begin;timeline->setPosition(cursor);showTime(cursor);}toggle->setFocus();});worker->start();}
